language: python

# sudo false implies containerized builds
sudo: false

python:
  - 2.7
  - 3.7
dist: xenial  # Required because there is no 3.7 archive

install:
- pip install .[all]
- pip install tox-travis

script:
- tox
